# Generated by Django 6.0.3 on 2026-03-06 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='摄像头名称')),
                ('location', models.CharField(max_length=200, verbose_name='监控区域/位置')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='视频流URL或本地路径')),
                ('threshold', models.FloatField(default=0.5, verbose_name='置信度阈值')),
                ('status', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('image', '图片'), ('video', '视频')], max_length=20, verbose_name='任务类型')),
                ('file_path', models.FileField(upload_to='uploads/tasks/', verbose_name='上传的文件')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '检测中'), ('completed', '已完成')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
        migrations.CreateModel(
            name='SmokingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.ImageField(upload_to='snapshots/', verbose_name='抓拍截图')),
                ('confidence', models.FloatField(verbose_name='YOLO置信度')),
                ('llm_report', models.TextField(blank=True, null=True, verbose_name='大模型分析报告')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='是否确认为吸烟(大模型复核结果)')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='报警时间')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.camera', verbose_name='关联摄像头')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.detectiontask', verbose_name='关联任务')),
            ],
        ),
    ]
