# Generated by Django 6.0.3 on 2026-03-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiontask',
            name='error_message',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='错误原因'),
        ),
        migrations.AddField(
            model_name='detectiontask',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='文件大小字节'),
        ),
        migrations.AddField(
            model_name='detectiontask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='detectiontask',
            name='process_time_ms',
            field=models.IntegerField(default=0, verbose_name='处理耗时毫秒'),
        ),
        migrations.AddField(
            model_name='detectiontask',
            name='resolution_h',
            field=models.IntegerField(default=0, verbose_name='高度'),
        ),
        migrations.AddField(
            model_name='detectiontask',
            name='resolution_w',
            field=models.IntegerField(default=0, verbose_name='宽度'),
        ),
        migrations.AlterField(
            model_name='detectiontask',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('processing', '检测中'), ('completed', '已完成'), ('failed', '任务中断')], default='pending', max_length=20),
        ),
    ]
