# Generated by Django 6.0.3 on 2026-03-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_detectiontask_error_message_detectiontask_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiontask',
            name='confidence_threshold',
            field=models.FloatField(default=0.5, verbose_name='置信度阈值'),
        ),
        migrations.AddField(
            model_name='detectiontask',
            name='device_name',
            field=models.CharField(default='GPU', max_length=80, verbose_name='运行设备'),
        ),
        migrations.AddField(
            model_name='detectiontask',
            name='model_name',
            field=models.CharField(default='Aero-YOLO-v8s', max_length=80, verbose_name='检测模型'),
        ),
    ]
