# Generated by Django 6.0.3 on 2026-03-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_detectiontask_confidence_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiontask',
            name='detections',
            field=models.JSONField(default=list, verbose_name='检测框'),
        ),
    ]
