# Generated by Django 6.0.3 on 2026-03-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_sharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiontask',
            name='annotated_file',
            field=models.FileField(blank=True, null=True, upload_to='results/tasks/', verbose_name='带框结果文件'),
        ),
    ]
