# Generated by Django 6.0.3 on 2026-03-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_detectiontask_annotated_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiontask',
            name='verify_status',
            field=models.CharField(choices=[('pending', '待核实'), ('confirmed', '已确认违规'), ('false_positive', '误报'), ('auto_passed', '正常/无需核实')], default='auto_passed', max_length=20, verbose_name='核实状态'),
        ),
    ]
