# Generated by Django 6.0.3 on 2026-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_detectiontask_verify_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectiontask',
            name='verify_status',
            field=models.CharField(choices=[('pending', '待核实'), ('verified', '已核实')], default='verified', max_length=20, verbose_name='核实状态'),
        ),
    ]
