# Generated by Django 6.0.3 on 2026-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_detectiontask_verify_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['-created_at'], 'verbose_name': '摄像头', 'verbose_name_plural': '摄像头'},
        ),
        migrations.RemoveField(
            model_name='camera',
            name='location',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='status',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='threshold',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='url',
        ),
        migrations.AddField(
            model_name='camera',
            name='confidence_threshold',
            field=models.FloatField(default=0.75, verbose_name='置信度阈值'),
        ),
        migrations.AddField(
            model_name='camera',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间'),
        ),
        migrations.AddField(
            model_name='camera',
            name='region',
            field=models.CharField(default='默认区域', max_length=120, verbose_name='所属区域'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(default='0', max_length=512, verbose_name='视频流地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=120, verbose_name='摄像头名称'),
        ),
    ]
