# Generated by Django 5.2.13 on 2026-04-26 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0011_alter_camera_id_alter_detectiontask_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('detection', '目标检测'), ('llm', '大语言模型'), ('strategy', '策略模块')], max_length=20, verbose_name='模型类型')),
                ('version', models.CharField(max_length=80, verbose_name='版本')),
                ('status', models.CharField(choices=[('enabled', '已启用'), ('connected', '已连接'), ('standby', '备用')], default='standby', max_length=20, verbose_name='状态')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='精度')),
                ('deploy_node', models.CharField(blank=True, default='', max_length=120, verbose_name='部署节点')),
                ('inference_threshold', models.FloatField(default=0.75, verbose_name='推理阈值')),
                ('response_mode', models.CharField(default='自动分析', max_length=40, verbose_name='响应模式')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否当前激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 模型',
                'verbose_name_plural': 'AI 模型',
                'ordering': ['model_type', '-is_active', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detectiontask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smokingrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ActiveModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inference_threshold', models.FloatField(default=0.75, verbose_name='推理阈值')),
                ('response_mode', models.CharField(default='自动分析', max_length=40, verbose_name='响应模式')),
                ('deploy_node', models.CharField(blank=True, default='', max_length=120, verbose_name='部署节点')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('detection_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_detection', to='detection.aimodel', verbose_name='当前检测模型')),
                ('llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_llm', to='detection.aimodel', verbose_name='当前大语言模型')),
            ],
            options={
                'verbose_name': '当前激活模型配置',
                'verbose_name_plural': '当前激活模型配置',
            },
        ),
    ]
