# Generated by Django 5.2.13 on 2026-04-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_aimodel_alter_camera_id_alter_detectiontask_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key', models.CharField(choices=[('qwen', '通义千问'), ('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('zhipu', '智谱 AI')], max_length=32, unique=True, verbose_name='服务标识')),
                ('service_name', models.CharField(max_length=64, verbose_name='服务名称')),
                ('base_url', models.CharField(max_length=255, verbose_name='Base URL')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API Key')),
                ('model_name', models.CharField(blank=True, default='', max_length=120, verbose_name='模型名称')),
                ('model_options', models.JSONField(default=list, verbose_name='模型选项')),
                ('api_key_url', models.CharField(blank=True, default='', max_length=255, verbose_name='API Key 获取地址')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('is_connected', models.BooleanField(default=False, verbose_name='连接状态')),
                ('request_timeout', models.PositiveIntegerField(default=30, verbose_name='请求超时秒数')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='最近测试时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '大模型服务配置',
                'verbose_name_plural': '大模型服务配置',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
